apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstateconfig{{ i }}
  namespace: {{ namespace }}
  labels:
    some-user-defined-label-name: some-user-defined-label-value
spec:
  config:
    interfaces:
      - name: eth0
        type: ethernet
        state: up
        mac-address: {{ mac_a }}
        ipv4:
          enabled: true
          address:
            - ip: 172.16.{{ c_octet }}.{{ d_octet }}
              prefix-length: 16
          dhcp: false
      - name: eth1
        type: ethernet
        state: up
        mac-address: {{ mac_b }}
        ipv4:
          enabled: true
          address:
            - ip: 172.17.{{ d_octet }}.{{ c_octet }}
              prefix-length: 16
          dhcp: false
    dns-resolver:
      config:
        server:
          - 1.1.1.1
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 172.16.1.1
          next-hop-interface: eth1
          table-id: 254
        - destination: 0.0.0.0/0
          next-hop-address: 172.17.1.1
          next-hop-interface: eth1
          table-id: 254
  interfaces:
    - name: "eth0"
      macAddress: "{{ mac_a }}"
    - name: "eth1"
      macAddress: "{{ mac_b }}"